apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tempmail-client-cert
  namespace: {{ .Release.Namespace }}
  annotations: 
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-10"
spec:
  secretName: tempmail-client-tls
  issuerRef:
    name: mongo-ca-issuer
    kind: ClusterIssuer
  commonName: "tempmail-app"